# -*- coding: utf-8 -*-
"""Data decomposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPijAT9LubN6wzxxjpZPXTRIWI2sKKas
"""

import pandas as pd

# 1) Citește fișierul sursă
df = pd.read_csv('/content/ai_adoption_70k.csv')

# 2) Definește coloanele pentru fiecare tabel

companies_cols = [
    'company_id',
    'industry',
    'country',
    'company_size'
]

company_ai_adoption_cols = [
    'response_id',
    'company_id',
    'survey_year',
    'quarter',
    'ai_adoption_rate',
    'ai_adoption_stage',
    'years_using_ai',
    'ai_primary_tool',
    'num_ai_tools_used',
    'ai_use_case',
    'ai_projects_active'
]

company_ai_governance_cols = [
    'response_id',
    'company_id',
    'survey_year',
    'quarter',
    'ai_training_hours',
    'ai_maturity_score',
    'ai_failure_rate',
    'ai_risk_management_score'
]

# 3) Creează cele 3 tabele

companies_pg = (
    df[companies_cols]
    .drop_duplicates(subset=['company_id'])
    .sort_values(by='company_id')
    .reset_index(drop=True)
)

company_ai_adoption_pg = (
    df[company_ai_adoption_cols]
    .copy()
    .sort_values(by='response_id')
    .reset_index(drop=True)
)

company_ai_governance_pg = (
    df[company_ai_governance_cols]
    .copy()
    .sort_values(by='response_id')
    .reset_index(drop=True)
)

# 4) Verificări rapide
print("companies_pg:", companies_pg.shape)
print("company_ai_adoption_pg:", company_ai_adoption_pg.shape)
print("company_ai_governance_pg:", company_ai_governance_pg.shape)

print("\nChei unice:")
print("companies_pg company_id unique:", companies_pg['company_id'].is_unique)
print("company_ai_adoption_pg response_id unique:", company_ai_adoption_pg['response_id'].is_unique)
print("company_ai_governance_pg response_id unique:", company_ai_governance_pg['response_id'].is_unique)

# 5) Salvează CSV-urile
companies_pg.to_csv('/content/companies_pg.csv', index=False)
company_ai_adoption_pg.to_csv('/content/company_ai_adoption_pg.csv', index=False)
company_ai_governance_pg.to_csv('/content/company_ai_governance_pg.csv', index=False)

print("\nFișiere salvate:")
print("/content/companies_pg.csv")
print("/content/company_ai_adoption_pg.csv")
print("/content/company_ai_governance_pg.csv")

from google.colab import files

files.download('/content/companies_pg.csv')
files.download('/content/company_ai_adoption_pg.csv')
files.download('/content/company_ai_governance_pg.csv')

import pandas as pd

# Citește fișierul sursă
df = pd.read_csv('/content/ai_adoption_70k.csv')

# =========================
# 1. companies_orcl
# =========================
companies_cols = [
    'company_id',
    'country',
    'company_size',
    'num_employees',
    'annual_revenue_usd_millions'
]

companies_orcl = (
    df[companies_cols]
    .drop_duplicates(subset=['company_id'])
    .sort_values(by='company_id')
    .reset_index(drop=True)
)

# =========================
# 2. company_workforce_impact_orcl
# =========================
workforce_cols = [
    'response_id',
    'company_id',
    'survey_year',
    'quarter',
    'remote_work_percentage',
    'employee_satisfaction_score',
    'task_automation_rate',
    'time_saved_per_week',
    'jobs_displaced',
    'jobs_created',
    'reskilled_employees'
]

company_workforce_impact_orcl = (
    df[workforce_cols]
    .copy()
    .sort_values(by='response_id')
    .reset_index(drop=True)
)

# =========================
# 3. company_business_outcomes_orcl
# =========================
business_cols = [
    'response_id',
    'company_id',
    'survey_year',
    'quarter',
    'productivity_change_percent',
    'revenue_growth_percent',
    'cost_reduction_percent',
    'innovation_score',
    'customer_satisfaction'
]

company_business_outcomes_orcl = (
    df[business_cols]
    .copy()
    .sort_values(by='response_id')
    .reset_index(drop=True)
)

# =========================
# Verificări rapide
# =========================
print("companies_orcl:", companies_orcl.shape)
print("company_workforce_impact_orcl:", company_workforce_impact_orcl.shape)
print("company_business_outcomes_orcl:", company_business_outcomes_orcl.shape)

print("\nChei unice:")
print("companies_orcl company_id unique:", companies_orcl['company_id'].is_unique)
print("company_workforce_impact_orcl response_id unique:", company_workforce_impact_orcl['response_id'].is_unique)
print("company_business_outcomes_orcl response_id unique:", company_business_outcomes_orcl['response_id'].is_unique)

# =========================
# Salvează CSV-urile
# =========================
companies_orcl.to_csv('/content/companies_orcl.csv', index=False)
company_workforce_impact_orcl.to_csv('/content/company_workforce_impact_orcl.csv', index=False)
company_business_outcomes_orcl.to_csv('/content/company_business_outcomes_orcl.csv', index=False)

print("\nFișiere salvate:")
print("/content/companies_orcl.csv")
print("/content/company_workforce_impact_orcl.csv")
print("/content/company_business_outcomes_orcl.csv")

from google.colab import files

files.download('/content/companies_orcl.csv')
files.download('/content/company_workforce_impact_orcl.csv')
files.download('/content/company_business_outcomes_orcl.csv')

import pandas as pd
import json

# 1) Citește fișierele sursă
country_df = pd.read_csv('/content/country_ai_index.csv')
industry_df = pd.read_csv('/content/ai_industry_summary.csv')

# 2) Păstrează doar coloanele necesare pentru MongoDB

country_cols = [
    'country',
    'region',
    'gdp_per_capita',
    'internet_penetration',
    'digital_maturity_index',
    'country_ai_policy',
    'ai_patent_filings_2024',
    'ai_researchers_per_million'
]

industry_cols = [
    'industry',
    'avg_ai_adoption_rate',
    'avg_ai_maturity_score',
    'avg_ai_failure_rate'
]

country_df = country_df[country_cols].copy()
industry_df = industry_df[industry_cols].copy()

# 3) Curăță duplicatele, dacă există
country_df = country_df.drop_duplicates(subset=['country']).reset_index(drop=True)
industry_df = industry_df.drop_duplicates(subset=['industry']).reset_index(drop=True)

# 4) Creează lista nested de benchmarkuri pe industrie
industry_benchmarks = []

for _, row in industry_df.iterrows():
    industry_doc = {
        "industry": row["industry"],
        "adoption": {
            "avg_ai_adoption_rate": None if pd.isna(row["avg_ai_adoption_rate"]) else float(row["avg_ai_adoption_rate"]),
            "avg_ai_maturity_score": None if pd.isna(row["avg_ai_maturity_score"]) else float(row["avg_ai_maturity_score"])
        },
        "risk": {
            "avg_ai_failure_rate": None if pd.isna(row["avg_ai_failure_rate"]) else float(row["avg_ai_failure_rate"])
        }
    }
    industry_benchmarks.append(industry_doc)

# 5) Creează documentele MongoDB: un document per țară
mongo_docs = []

for _, row in country_df.iterrows():
    doc = {
        "country": row["country"],
        "region": row["region"],
        "macro_indicators": {
            "gdp_per_capita": None if pd.isna(row["gdp_per_capita"]) else float(row["gdp_per_capita"]),
            "internet_penetration": None if pd.isna(row["internet_penetration"]) else float(row["internet_penetration"]),
            "digital_maturity_index": None if pd.isna(row["digital_maturity_index"]) else float(row["digital_maturity_index"])
        },
        "ai_ecosystem": {
            "country_ai_policy": row["country_ai_policy"],
            "ai_patent_filings_2024": None if pd.isna(row["ai_patent_filings_2024"]) else int(row["ai_patent_filings_2024"]),
            "ai_researchers_per_million": None if pd.isna(row["ai_researchers_per_million"]) else float(row["ai_researchers_per_million"])
        },
        "industry_benchmarks": industry_benchmarks
    }
    mongo_docs.append(doc)

# 6) Salvează ca JSON array
output_path = '/content/country_ai_profiles.json'

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(mongo_docs, f, ensure_ascii=False, indent=2)

print(f"JSON generat cu succes: {output_path}")
print(f"Număr documente: {len(mongo_docs)}")

# 7) Verificare dimensiune fișier
import os
size_mb = os.path.getsize(output_path) / (1024 * 1024)
print(f"Dimensiune fișier: {size_mb:.2f} MB")

from google.colab import files
files.download('/content/country_ai_profiles.json')

import pandas as pd

# 1. Citește fișierul sursă
df = pd.read_csv('/content/ai_adoption_70k.csv')

# 2. Păstrează doar coloanele necesare
cols_needed = [
    'country',
    'survey_year',
    'quarter',
    'company_id',
    'ai_adoption_rate',
    'ai_maturity_score',
    'productivity_change_percent',
    'jobs_displaced',
    'jobs_created'
]

df = df[cols_needed].copy()

# 3. Creează agregarea
country_quarter_summary = (
    df.groupby(['country', 'survey_year', 'quarter'], as_index=False)
      .agg(
          num_companies=('company_id', 'nunique'),
          avg_ai_adoption_rate=('ai_adoption_rate', 'mean'),
          avg_ai_maturity_score=('ai_maturity_score', 'mean'),
          avg_productivity_change_percent=('productivity_change_percent', 'mean'),
          total_jobs_displaced=('jobs_displaced', 'sum'),
          total_jobs_created=('jobs_created', 'sum')
      )
)

# 4. Rotunjire pentru coloanele numerice de tip medie
country_quarter_summary['avg_ai_adoption_rate'] = country_quarter_summary['avg_ai_adoption_rate'].round(2)
country_quarter_summary['avg_ai_maturity_score'] = country_quarter_summary['avg_ai_maturity_score'].round(3)
country_quarter_summary['avg_productivity_change_percent'] = country_quarter_summary['avg_productivity_change_percent'].round(2)

# 5. Sortează frumos
country_quarter_summary = country_quarter_summary.sort_values(
    by=['country', 'survey_year', 'quarter']
).reset_index(drop=True)

# 6. Salvează într-un Excel cu un singur sheet
output_path = '/content/ai_reporting_local.xlsx'

with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    country_quarter_summary.to_excel(
        writer,
        sheet_name='country_quarter_summary',
        index=False
    )

print("Fișier Excel generat:", output_path)
print("Dimensiune tabel agregat:", country_quarter_summary.shape)

# 7. Preview
print(country_quarter_summary.head(10))

from google.colab import files
files.download('/content/ai_reporting_local.xlsx')