SELECT table_name
FROM user_tables
ORDER BY table_name;

SELECT COUNT(*) FROM COMPANIES;
SELECT COUNT(*) FROM COMPANY_BUSINESS_OUTCOMES;
SELECT COUNT(*) FROM COMPANY_WORKFORCE_IMPACT;

ALTER TABLE COMPANIES
ADD CONSTRAINT PK_COMPANIES PRIMARY KEY (company_id);

ALTER TABLE COMPANY_BUSINESS_OUTCOMES
ADD CONSTRAINT PK_COMPANY_BUS_OUT PRIMARY KEY (response_id);

ALTER TABLE COMPANY_WORKFORCE_IMPACT
ADD CONSTRAINT PK_COMPANY_WORKFORCE PRIMARY KEY (response_id);

ALTER TABLE COMPANY_BUSINESS_OUTCOMES
ADD CONSTRAINT FK_BUS_OUT_COMPANY
FOREIGN KEY (company_id)
REFERENCES COMPANIES(company_id);

ALTER TABLE COMPANY_WORKFORCE_IMPACT
ADD CONSTRAINT FK_WORKFORCE_COMPANY
FOREIGN KEY (company_id)
REFERENCES COMPANIES(company_id);


SELECT constraint_name, constraint_type, table_name
FROM user_constraints
WHERE table_name IN (
    'COMPANIES',
    'COMPANY_BUSINESS_OUTCOMES',
    'COMPANY_WORKFORCE_IMPACT'
)
ORDER BY table_name, constraint_type;