CREATE OR REPLACE VIEW COMPANIES_VIEW AS
SELECT *
FROM COMPANIES@ai_data_db;

CREATE OR REPLACE VIEW COMPANY_BUSINESS_OUTCOMES_VIEW AS
SELECT *
FROM COMPANY_BUSINESS_OUTCOMES@ai_data_db;

CREATE OR REPLACE VIEW COMPANY_WORKFORCE_IMPACT_VIEW AS
SELECT *
FROM COMPANY_WORKFORCE_IMPACT@ai_data_db;

SELECT * FROM COMPANIES_VIEW WHERE ROWNUM <= 5;
SELECT * FROM COMPANY_BUSINESS_OUTCOMES_VIEW WHERE ROWNUM <= 5;
SELECT * FROM COMPANY_WORKFORCE_IMPACT_VIEW WHERE ROWNUM <= 5;