SELECT name FROM v$database;
SHOW CON_NAME;

CREATE USER AI_DATA IDENTIFIED BY oracle;

GRANT CREATE SESSION TO AI_DATA;
GRANT CREATE TABLE TO AI_DATA;
GRANT CREATE VIEW TO AI_DATA;
GRANT CREATE SEQUENCE TO AI_DATA;
GRANT CREATE PROCEDURE TO AI_DATA;
GRANT UNLIMITED TABLESPACE TO AI_DATA;

SELECT username
FROM all_users
WHERE username = 'AI_DATA';


SELECT username
FROM all_users
WHERE username = 'FDBO';

CREATE USER FDBO IDENTIFIED BY oracle;

GRANT CREATE SESSION TO FDBO;
GRANT CREATE TABLE TO FDBO;
GRANT CREATE VIEW TO FDBO;
GRANT CREATE SEQUENCE TO FDBO;
GRANT CREATE PROCEDURE TO FDBO;
GRANT UNLIMITED TABLESPACE TO FDBO;