

  CREATE TABLE "AI_DATA"."COMPANIES" 
   (	"COMPANY_ID" VARCHAR2(26),  
	"COUNTRY" VARCHAR2(26),  
	"COMPANY_SIZE" VARCHAR2(26),  
	"NUM_EMPLOYEES" NUMBER(38,0),  
	"ANNUAL_REVENUE_USD_MILLIONS" NUMBER(38,2),  
	 CONSTRAINT "PK_COMPANIES" PRIMARY KEY ("COMPANY_ID") 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "AI_DATA"."COMPANY_BUSINESS_OUTCOMES" 
   (	"RESPONSE_ID" NUMBER(38,0),  
	"COMPANY_ID" VARCHAR2(26),  
	"SURVEY_YEAR" NUMBER(38,0),  
	"QUARTER" VARCHAR2(26),  
	"PRODUCTIVITY_CHANGE_PERCENT" NUMBER(38,2),  
	"REVENUE_GROWTH_PERCENT" NUMBER(38,2),  
	"COST_REDUCTION_PERCENT" NUMBER(38,2),  
	"INNOVATION_SCORE" NUMBER(38,0),  
	"CUSTOMER_SATISFACTION" NUMBER(38,2),  
	 CONSTRAINT "PK_COMPANY_BUS_OUT" PRIMARY KEY ("RESPONSE_ID") 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_BUS_OUT_COMPANY" FOREIGN KEY ("COMPANY_ID") 
	  REFERENCES "AI_DATA"."COMPANIES" ("COMPANY_ID") ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "AI_DATA"."COMPANY_WORKFORCE_IMPACT" 
   (	"RESPONSE_ID" NUMBER(38,0),  
	"COMPANY_ID" VARCHAR2(26),  
	"SURVEY_YEAR" NUMBER(38,0),  
	"QUARTER" VARCHAR2(26),  
	"REMOTE_WORK_PERCENTAGE" NUMBER(38,2),  
	"EMPLOYEE_SATISFACTION_SCORE" NUMBER(38,2),  
	"TASK_AUTOMATION_RATE" NUMBER(38,2),  
	"TIME_SAVED_PER_WEEK" NUMBER(38,2),  
	"JOBS_DISPLACED" NUMBER(38,0),  
	"JOBS_CREATED" NUMBER(38,0),  
	"RESKILLED_EMPLOYEES" NUMBER(38,0),  
	 CONSTRAINT "PK_COMPANY_WORKFORCE" PRIMARY KEY ("RESPONSE_ID") 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_WORKFORCE_COMPANY" FOREIGN KEY ("COMPANY_ID") 
	  REFERENCES "AI_DATA"."COMPANIES" ("COMPANY_ID") ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

