
OWNER                                                                                                                            TABLE_NAME                                                                                                                        COLUMN_ID COLUMN_NAME                                                                                                                      DATA_TYPE                                                                                                                        DATA_LENGTH DATA_PRECISION DATA_SCALE N
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ---------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------- -------------- ---------- -
FDBO                                                                                                                             COMPANIES_VIEW                                                                                                                            1 COMPANY_ID                                                                                                                       VARCHAR2                                                                                                                                  26                           N
FDBO                                                                                                                             COMPANIES_VIEW                                                                                                                            2 COUNTRY                                                                                                                          VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANIES_VIEW                                                                                                                            3 COMPANY_SIZE                                                                                                                     VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANIES_VIEW                                                                                                                            4 NUM_EMPLOYEES                                                                                                                    NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANIES_VIEW                                                                                                                            5 ANNUAL_REVENUE_USD_MILLIONS                                                                                                      NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            1 RESPONSE_ID                                                                                                                      NUMBER                                                                                                                                    22             38          0 N
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            2 COMPANY_ID                                                                                                                       VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            3 SURVEY_YEAR                                                                                                                      NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            4 QUARTER                                                                                                                          VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            5 PRODUCTIVITY_CHANGE_PERCENT                                                                                                      NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            6 REVENUE_GROWTH_PERCENT                                                                                                           NUMBER                                                                                                                                    22             38          2 Y

OWNER                                                                                                                            TABLE_NAME                                                                                                                        COLUMN_ID COLUMN_NAME                                                                                                                      DATA_TYPE                                                                                                                        DATA_LENGTH DATA_PRECISION DATA_SCALE N
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ---------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------- -------------- ---------- -
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            7 COST_REDUCTION_PERCENT                                                                                                           NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            8 INNOVATION_SCORE                                                                                                                 NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANY_BUSINESS_OUTCOMES_VIEW                                                                                                            9 CUSTOMER_SATISFACTION                                                                                                            NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             1 RESPONSE_ID                                                                                                                      NUMBER                                                                                                                                    22             38          0 N
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             2 COMPANY_ID                                                                                                                       VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             3 SURVEY_YEAR                                                                                                                      NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             4 QUARTER                                                                                                                          VARCHAR2                                                                                                                                  26                           Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             5 REMOTE_WORK_PERCENTAGE                                                                                                           NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             6 EMPLOYEE_SATISFACTION_SCORE                                                                                                      NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             7 TASK_AUTOMATION_RATE                                                                                                             NUMBER                                                                                                                                    22             38          2 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             8 TIME_SAVED_PER_WEEK                                                                                                              NUMBER                                                                                                                                    22             38          2 Y

OWNER                                                                                                                            TABLE_NAME                                                                                                                        COLUMN_ID COLUMN_NAME                                                                                                                      DATA_TYPE                                                                                                                        DATA_LENGTH DATA_PRECISION DATA_SCALE N
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ---------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------- -------------- ---------- -
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                             9 JOBS_DISPLACED                                                                                                                   NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                            10 JOBS_CREATED                                                                                                                     NUMBER                                                                                                                                    22             38          0 Y
FDBO                                                                                                                             COMPANY_WORKFORCE_IMPACT_VIEW                                                                                                            11 RESKILLED_EMPLOYEES                                                                                                              NUMBER                                                                                                                                    22             38          0 Y

25 rows selected. 

